In [1]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series(list('abca'))
s.head()

0    a
1    b
2    c
3    a
dtype: object

In [4]:
pd.get_dummies(s)

a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0

In [7]:
s1 = ['a', 'b', np.nan]
s1

['a', 'b', nan]

In [8]:
pd.get_dummies(s1)

a    b
0  1.0  0.0
1  0.0  1.0
2  0.0  0.0

In [9]:
pd.get_dummies(s1, dummy_na=True)

a    b  NaN
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [11]:
df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
                    'C': [1, 2, 3]})
df.head()

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [16]:
dt = pd.get_dummies(df)
dt

C  A_a  A_b  B_a  B_b  B_c
0  1  1.0  0.0  0.0  1.0  0.0
1  2  0.0  1.0  1.0  0.0  0.0
2  3  1.0  0.0  0.0  0.0  1.0

In [13]:
pd.get_dummies(df, prefix=['col1', 'col2'])

C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1     1.0     0.0     0.0     1.0     0.0
1  2     0.0     1.0     1.0     0.0     0.0
2  3     1.0     0.0     0.0     0.0     1.0

In [14]:
pd.Series(list('abcaa'))

0    a
1    b
2    c
3    a
4    a
dtype: object

In [18]:
pd.concat([df,dt],axis=1)

A  B  C  C  A_a  A_b  B_a  B_b  B_c
0  a  b  1  1  1.0  0.0  0.0  1.0  0.0
1  b  a  2  2  0.0  1.0  1.0  0.0  0.0
2  a  c  3  3  1.0  0.0  0.0  0.0  1.0

In [48]:
mu, sigma = 0, 0.1 # mean and standard deviation
s3 = np.random.normal(mu, sigma, (5,2))
s3

array([[-0.00755486,  0.06601775],
       [-0.14245183,  0.15675006],
       [ 0.22399784, -0.01891616],
       [ 0.1158328 , -0.0757677 ],
       [ 0.22152505, -0.0255821 ]])

In [47]:
class sig(object):
    def __init__(self):
        self.function = self.sigmoid
    def sigmoid(self,x):
        return 1+x
tt = sig()
tt.function(10)

11

In [2]:
a = 10 
b = [1,2]
c = np.dot(a,b)
c

array([10, 20])

In [5]:
d = c * (1 - c)
d

array([ -90, -380])

In [7]:
f = a * c * d
f

array([ -9000, -76000])

In [9]:
f[:,None]

array([[ -9000],
       [-76000]])